### ISSUE TITLE
Doesn't deal with exceptions in the action block

### ISSUE THREAD

**Issue by prydonius** [prydonius/spinning_cursor#1]
```
irb(main):001:0> require "spinning_cursor"
=> true
irb(main):002:0> def spin
irb(main):003:1> SpinningCursor.start do
irb(main):004:2* banner "Code with exception"
irb(main):005:2> action { sleep 2 ; raise "oh no!" }
irb(main):006:2> end
irb(main):007:1> end
=> nil
irb(main):008:0> spin
Code with exception \RuntimeError: oh no!
    from (irb):5:in `block (2 levels) in spin'
    from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/spinning_cursor-0.1.0.rc1/lib/spinning_cursor.rb:26:in `instance_eval'
    from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/spinning_cursor-0.1.0.rc1/lib/spinning_cursor.rb:26:in `start'
    from (irb):3:in `spin'
    from (irb):8
    from /usr/local/Cellar/ruby/1.9.3-p125/bin/irb:12:in `<main>'
Code with exception |
```

Just continues on spinning.

**Comment by prydonius** [comment]
Fixed as of fd63cf6.
