### ISSUE TITLE
Failing test 1.8.7 (spinner should cycle through correctly)

### ISSUE THREAD

**Issue by prydonius** [prydonius/spinning_cursor#25]
1) Failure:
test: spinner should cycle through correctly. (TestSpinningCursorCursor)
    [/home/travis/build/prydonius/spinning_cursor/test/test_cursors.rb:104:in `__bind_1374946262_192960'
     ./test/helper.rb:35:in`capture_stdout'
     /home/travis/build/prydonius/spinning_cursor/test/test_cursors.rb:88:in `__bind_1374946262_192960'
     /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/shoulda-context-1.1.4/lib/shoulda/context/context.rb:400:in`call'
     /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/shoulda-context-1.1.4/lib/shoulda/context/context.rb:400:in `test: spinner should cycle through correctly. ']:
<"\r\e[0K|\r\e[0K/\r\e[0K-\r\e[0K\"> expected but was
<"\r\e[0K|\r\e[0K/\r\e[0K-">.

https://travis-ci.org/prydonius/spinning_cursor/jobs/9556322

**Comment by prydonius** [comment]
Nope, failed a second time. Setting milestone to v0.2.1
